name: ci-pythonWithProstgre
'on':
  push:
    branches:
      - main
    paths:
      - '**/pythonWithProstgre/**'
env:
  DOCKER_FILE_PATH: ./pythonWithProstgre/Dockerfile
  DOCKER_BUILD_CONTEXT: pythonWithProstgre
  CONTAINER_NAME: pythonpostgre
  REPOSITORY_NAME: pythonpostgre
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CR_LOGIN_SERVER }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build, test and push image to container registry
        run: |-
          docker build ${{ env.DOCKER_BUILD_CONTEXT }} -f ${{ env.DOCKER_FILE_PATH }} -t ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:test
          docker push ${{ secrets.CR_LOGIN_SERVER }}/${{ env.REPOSITORY_NAME }}:test
